// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;
export function GetOverview():Promise<{
    settingsPath: string;
    desktopCaptureEnabled: boolean;
    activityLogging: boolean;
    activeLanguage: string;
    lastRefresh: string;
    activitySample: Array<{
        id: string;
        category: string;
        description: string;
        timestamp: string;
        confidence: number;
    }>;
    connectionStatus?: {
        healthy: boolean;
        message: string;
    } | null;
}>;
export function GetRecentActivity():Promise<Array<{
    id: string;
    category: string;
    description: string;
    timestamp: string;
    confidence: number;
}>>;
export function GetSettings():Promise<{
    apiBaseUrl: string;
    apiKey: string;
    model: string;
    organization?: string;
    language: string;
    desktopCaptureEnabled: boolean;
    activityLogging: boolean;
}>;
export function SaveSettings(arg1:{
    apiBaseUrl: string;
    apiKey: string;
    model: string;
    organization?: string;
    language: string;
    desktopCaptureEnabled: boolean;
    activityLogging: boolean;
}):Promise<{
    apiBaseUrl: string;
    apiKey: string;
    model: string;
    organization?: string;
    language: string;
    desktopCaptureEnabled: boolean;
    activityLogging: boolean;
}>;
export function TestLLMConnection(arg1:{
    apiBaseUrl: string;
    apiKey: string;
    model: string;
    organization?: string;
    language: string;
    desktopCaptureEnabled: boolean;
    activityLogging: boolean;
}):Promise<{
    healthy: boolean;
    message: string;
}>;
