// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;
export function GetOverview():Promise<{
    settingsPath: string;
    desktopCaptureEnabled: boolean;
    activityLogging: boolean;
    activeLanguage: string;
    lastRefresh: string;
    activitySample: Array<{
        id: string;
        category: string;
        description: string;
        timestamp: string;
        confidence: number;
    }>;
    connectionStatus?: {
        healthy: boolean;
        message: string;
    } | null;
}>;
export function GetRecentActivity():Promise<Array<{
    id: string;
    category: string;
    description: string;
    timestamp: string;
    confidence: number;
}>>;
export function GetSettings():Promise<{
    apiBaseUrl: string;
    apiKey: string;
    model: string;
    organization?: string;
    language: string;
    desktopCaptureEnabled: boolean;
    activityLogging: boolean;
    displayName?: string;
    avatarUrl?: string;
    avatarData?: string;
    accountEmail?: string;
    preferredLLMVendor?: string;
    requestTimeoutSeconds?: number;
    maxRetries?: number;
    networkProxy?: string;
    allowUntrustedCertificates?: boolean;
    automationBrowser: string;
    browserProfilePath?: string;
    backgroundAutomation: boolean;
}>; 
export function SaveSettings(arg1:{
    apiBaseUrl: string;
    apiKey: string;
    model: string;
    organization?: string;
    language: string;
    desktopCaptureEnabled: boolean;
    activityLogging: boolean;
    displayName?: string;
    avatarUrl?: string;
    avatarData?: string;
    accountEmail?: string;
    preferredLLMVendor?: string;
    requestTimeoutSeconds?: number;
    maxRetries?: number;
    networkProxy?: string;
    allowUntrustedCertificates?: boolean;
    automationBrowser: string;
    browserProfilePath?: string;
    backgroundAutomation: boolean;
}):Promise<{
    apiBaseUrl: string;
    apiKey: string;
    model: string;
    organization?: string;
    language: string;
    desktopCaptureEnabled: boolean;
    activityLogging: boolean;
    displayName?: string;
    avatarUrl?: string;
    avatarData?: string;
    accountEmail?: string;
    preferredLLMVendor?: string;
    requestTimeoutSeconds?: number;
    maxRetries?: number;
    networkProxy?: string;
    allowUntrustedCertificates?: boolean;
    automationBrowser: string;
    browserProfilePath?: string;
    backgroundAutomation: boolean;
}>; 
export function TestLLMConnection(arg1:{
    apiBaseUrl: string;
    apiKey: string;
    model: string;
    organization?: string;
    language: string;
    desktopCaptureEnabled: boolean;
    activityLogging: boolean;
    displayName?: string;
    avatarUrl?: string;
    avatarData?: string;
    accountEmail?: string;
    preferredLLMVendor?: string;
    requestTimeoutSeconds?: number;
    maxRetries?: number;
    networkProxy?: string;
    allowUntrustedCertificates?: boolean;
    automationBrowser: string;
    browserProfilePath?: string;
    backgroundAutomation: boolean;
}):Promise<{
    healthy: boolean;
    message: string;
}>;
export function GetSession():Promise<{
    authenticated: boolean;
    profile?: {
        displayName: string;
        email?: string;
        avatarUrl?: string;
        avatarData?: string;
        lastLogin?: string;
    } | null;
}>;
export function Login(arg1:{
    username: string;
    email?: string;
    password: string;
}):Promise<{
    authenticated: boolean;
    profile?: {
        displayName: string;
        email?: string;
        avatarUrl?: string;
        avatarData?: string;
        lastLogin?: string;
    } | null;
}>;
export function Logout():Promise<{
    authenticated: boolean;
    profile?: {
        displayName: string;
        email?: string;
        avatarUrl?: string;
        avatarData?: string;
        lastLogin?: string;
    } | null;
}>;
